module rattpack.pkg.lockfile;

import rattpack.pkg.manifest : validatePackageName;
import rattpack.diagnostic;
import rattpack.rt.sys : atomicWrite;
import toml;
import std.file;
import std.json : JSONValue;
import std.algorithm : sort, all, canFind;
import std.string : replace;

struct LockedPackage
{
    string name;
    string version_;
    string source;
    string url;
    string revision;
    string checksum;
    string treeHash;
    string identity;
    string[] dependencies;
}

struct Lockfile
{
    string project;
    string manifestHash;
    LockedPackage[] entries;
}

private string quote(string value) @safe
{
    return JSONValue(value).toString.replace(`\/`, `/`);
}

void writeLock(string path, Lockfile lock)
{
    string text = "# Generated by rattpkg; deterministic and safe to commit for applications.\n"
        ~ "lock_version = 1\nproject = " ~ quote(
                lock.project) ~ "\nmanifest_hash = " ~ quote(lock.manifestHash) ~ "\n";
    lock.entries.sort!((a, b) => a.name < b.name);
    foreach (entry; lock.entries)
    {
        text ~= "\n[[package]]\n";
        foreach (pair; [
                ["name", entry.name], ["version", entry.version_],
                ["source", entry.source], ["url", entry.url],
                ["revision", entry.revision], ["sha256", entry.checksum],
                ["tree_hash", entry.treeHash], ["identity", entry.identity]
            ])
            text ~= pair[0] ~ " = " ~ quote(pair[1]) ~ "\n";
        text ~= "dependencies = " ~ JSONValue(entry.dependencies).toString ~ "\n";
    }
    atomicWrite(path, text);
}

Lockfile readLock(string path)
{
    if (!exists(path))
        fail("E_PACKAGE", "lockfile not found; run rattpkg resolve: " ~ path);
    try
    {
        auto table = parseTOML(readText(path)).table;
        if (table["lock_version"].integer != 1)
            fail("E_PACKAGE", "unsupported lockfile version");
        Lockfile lock;
        lock.project = table["project"].str;
        lock.manifestHash = table["manifest_hash"].str;
        if (auto packages = "package" in table)
            foreach (value; packages.array)
            {
                auto v = value.table;
                LockedPackage entry;
                entry.name = v["name"].str;
                validatePackageName(entry.name);
                entry.version_ = v["version"].str;
                entry.source = v["source"].str;
                entry.url = v["url"].str;
                entry.revision = v["revision"].str;
                entry.checksum = v["sha256"].str;
                entry.treeHash = v["tree_hash"].str;
                entry.identity = v["identity"].str;
                if (entry.treeHash.length != 64
                        || !entry.treeHash.all!(c => "0123456789abcdef".canFind(c)))
                    fail("E_PACKAGE", "invalid tree hash in lockfile");
                foreach (dep; v["dependencies"].array)
                    entry.dependencies ~= dep.str;
                foreach (other; lock.entries)
                    if (other.name == entry.name)
                        fail("E_PACKAGE", "duplicate package in lockfile");
                lock.entries ~= entry;
            }
        return lock;
    }
    catch (Diagnostic d)
    {
        throw d;
    }
    catch (Exception e)
    {
        fail("E_PACKAGE", e.msg, Location(path));
    }
    return Lockfile.init;
}
